services:
  - type: web
    name: farecal
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        value: farecal_db
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAX_DISTANCE_KM
        value: "500"